version: '3.7'
volumes:
    airflowdb: {}
services:
    postgres:
        image: postgres:11.5
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
          - airflowdb:/var/lib/postgresql/data
    webserver:
        build: .
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ./dags:/opt/airflow/dags
            - ./kube:/tmp/k8s/minikube
            - ./airflow.cfg:/opt/airflow/airflow.cfg
        ports:
            - "8080:8080"
        command: embedded
        healthcheck:
            test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
            interval: "20s"
            timeout: "20s"
            retries: 3

