apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: airflow-scheduler
  labels:
    app: airflow-scheduler
spec:
  serviceName: airflow-scheduler
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      serviceAccountName: job-trigger-sa
      containers:
      - name: airflow-dags-sync
        imagePullPolicy: IfNotPresent
        image: "k8s.gcr.io/git-sync:v3.1.0"

        securityContext:
          runAsUser: 65534
          runAsNonRoot: true
          readOnlyRootFilesystem: true
        env:
          - name: GIT_SYNC_REPO
            value: https://github.com/skhatri/airflow-example-dags
          - name: GIT_SYNC_BRANCH
            value: main
          - name: AIRFLOW__KUBERNETES__GIT_SUBPATH
            value: dags
          - name: GIT_SYNC_WAIT
            value: "300"
          - name: GIT_SYNC_USERNAME
            value: skhatri
          - name: GIT_SYNC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: airflow-secrets
                key: GIT_TOKEN
          - name: GIT_SYNC_ROOT
            value: /data/checkout
          - name: GIT_SYNC_DEST
            value: work-dir
        volumeMounts:
          - mountPath: /data/checkout
            name: airflow-dags
          - mountPath: /tmp
            name: tmp-dir

      - name: airflow
        imagePullPolicy: IfNotPresent
        image: "skhatri/airflow:2.0.10"
        args: 
        - scheduler
        securityContext:
          runAsUser: 50000
          runAsNonRoot: true 
          readOnlyRootFilesystem: true
        ports:
          - name: logport
            containerPort: 8973
        resources:
          limits:
            cpu: "600m"
            memory: 1600Mi
          requests:
            cpu: "600m"
            memory: 1600Mi  
        env:
        - name: "AIRFLOW__CORE__EXECUTOR"
          value: "LocalExecutor"
        - name: "AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL"
          value: "60"
        - name: "AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT"
          value: "False"
        - name: "AIRFLOW__WEBSERVER__LOG_FETCH_TIMEOUT_SEC"
          value: "60"
        - name: "AIRFLOW__CORE__REMOTE_LOGGING"
          value: "False"

        - name: "AIRFLOW__KUBERNETES__IN_CLUSTER"
          value: "True"
        - name: "AIRFLOW__KUBERNETES__DELETE_WORKER_PODS"
          value: "True"
        - name: "AIRFLOW__ADMIN__HIDE_SENSITIVE_VARIABLE_FIELDS"
          value: "True"
        - name: "AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION"
          value: "True"
        - name: "AIRFLOW__KUBERNETES__DAGS_IN_IMAGE"
          value: "False"
        - name: "AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME"
          value: "job-trigger-sa"
        - name: "AIRFLOW_TEST_CONFIG"
          value: "/opt/airflow-work-dir/unittests.cfg"
        - name: "AIRFLOW_CONFIG"
          value: "/opt/airflow/airflow.cfg"
        - name: "AIRFLOW__CORE__DAGS_FOLDER"
          value: "/opt/app/dags-checkout/work-dir"
        - name: "AIRFLOW__LOGGING__BASE_LOG_FOLDER"
          value: "/opt/app/logs"
        - name: "AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT"
          value: "300"
        - name: "AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT"
          value: "300"
        - name: "SPARK_LAUNCHER_IMAGE"
          value: "skhatri/spark:3.1.1"
        - name: "SPARK_JOB_IMAGE"
          value: "skhatri/spark-k8s-hello:1.0.11"
        - name: "AUTH_TYPE"
          value: "DB"
        volumeMounts:
        - mountPath: /opt/app/dags-checkout
          name: airflow-dags
        - mountPath: /opt/app/logs
          name: airflow-logs-dir
        - mountPath: /opt/airflow
          name: airflow-home
        - mountPath: /opt/work
          name: work-dir
        - mountPath: /tmp
          name: tmp-dir
        - mountPath: /opt/airflow-work-dir
          name: airflow-work-dir

      volumes:
      - name: secrets-mount
        secret:
          secretName: airflow-secrets
          items:
          - key: GIT_TOKEN
            path: git_token
      - name: airflow-dags
        emptyDir: {}
      - name: airflow-home
        emptyDir: {}
      - name: airflow-logs-dir
        emptyDir: {}
      - name: tmp-dir
        emptyDir: {}
      - name: airflow-work-dir
        emptyDir: {}
      - name: work-dir
        emptyDir: {}

