apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: airflow
  labels:
    app: airflow
spec:
  serviceName: airflow
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      serviceAccountName: job-trigger-sa
      initContainers:
      - name: airflow-dags
        imagePullPolicy: IfNotPresent
        image: "kubesailmaker/git-checkout:0.6"
        command:
        - /bin/sh
        args:
        - -c
        - "cd /data/checkout; /opt/app/git-checkout.sh"
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
          readOnlyRootFilesystem: true
        env:
        - name: GIT_PROJECTS
          value: "skhatri/airflow-example-dags.git,/data/checkout/airflow-example-dags,main"
        - name: GIT_PROTOCOL
          value: "https"
        - name: "GIT_BASE"
          value: "github.com"
        - name: GIT_USER
          value: "skhatri"
        - name: GIT_TOKEN_FILE
          value: "/data/secrets/git_token"
        volumeMounts:
        - mountPath: /data/checkout
          name: airflow-dags
        - mountPath: /data/secrets
          name: secrets-mount
        - name: tmp-dir
          mountPath: /tmp
      containers:
      - name: airflow
        imagePullPolicy: IfNotPresent
        #image: "kubesailmaker/airflow:2.0.0-python3.8-b3"
        image: "__IMAGE_NAME__:__IMAGE_TAG__"
        args: 
        - embedded
        securityContext:
          runAsUser: 50000
          runAsNonRoot: true 
          readOnlyRootFilesystem: true
        ports:
        - name: airflowport
          containerPort: 8280
        resources:
          limits:
            cpu: "600m"
            memory: 1600Mi
          requests:
            cpu: "600m"
            memory: 1600Mi  
        env:
        - name: LOADEX
          value: "n"
        - name: "AIRFLOW__CORE__EXECUTOR"
          value: "SequentialExecutor"
        - name: AIRFLOW__KUBERNETES__IN_CLUSTER
          value: "True"
        - name: "AIRFLOW__KUBERNETES__DELETE_WORKER_PODS"
          value: "True"
        - name: "AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY"
          value: "__IMAGE_WORKER_NAME__"
        - name: "AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG"
          value: "__IMAGE_TAG__"
        - name: "AIRFLOW__ADMIN__HIDE_SENSITIVE_VARIABLE_FIELDS"
          value: "True"
        - name: "AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION"
          value: "True"
        - name: "AIRFLOW__WEBSERVER__NAVBAR_COLOR"
          value: "#9fca08"
        - name: "AIRFLOW__KUBERNETES__DAGS_IN_IMAGE"
          value: "True"          
        - name: "AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME"
          value: "job-trigger-sa"
        - name: "AIRFLOW_TEST_CONFIG"
          value: "/opt/airflow-work-dir/unittests.cfg"
        - name: "AIRFLOW_CONFIG"
          value: "/opt/airflow/airflow.cfg"
        - name: "WEBSERVER_CONFIG"
          value: "/opt/airflow/webserver_config.py"
        - name: "AIRFLOW__CORE__DAGS_FOLDER"
          value: "/opt/app/dags"
        - name: "AIRFLOW__LOGGING__BASE_LOG_FOLDER"
          value: "/opt/app/logs"
        - name: "AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT"
          value: "300"
        - name: "AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT"
          value: "300"
        - name: "SPARK_LAUNCHER_IMAGE"
          value: "__SPARK_LAUNCHER_IMAGE__"
        - name: "SPARK_JOB_IMAGE"
          value: "__SPARK_JOB_IMAGE__"
        - name: "AUTH_TYPE"
          value: "DB"
        volumeMounts:
        - mountPath: /opt/app/dags
          name: airflow-dags
        - mountPath: /opt/app/logs
          name: airflow-logs-dir
        - mountPath: /opt/airflow
          name: airflow-home
        - mountPath: /opt/work
          name: work-dir
        - mountPath: /tmp
          name: tmp-dir
        - mountPath: /opt/airflow-work-dir
          name: airflow-work-dir

      volumes:
      - name: secrets-mount
        secret:
          secretName: airflow-secrets
          items:
          - key: GIT_TOKEN
            path: git_token
      - name: airflow-dags
        emptyDir: {}
      - name: airflow-home
        emptyDir: {}
      - name: airflow-logs-dir
        emptyDir: {}
      - name: tmp-dir
        emptyDir: {}
      - name: airflow-work-dir
        emptyDir: {}
      - name: work-dir
        emptyDir: {}         
---
kind: Service
apiVersion: v1
metadata:
  name: airflow
spec:
  selector:
    app: airflow
  ports:
  - name: airflowport
    protocol: TCP
    port: 8280
    targetPort: airflowport
    nodePort: 31800
  type: NodePort
