apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: policies-job
spec:
  hostIPC: false
  hostPID: false
  hostNetwork: false
  privileged: false
  readOnlyRootFilesystem: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - min: 999
        max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 999
        max: 65535
  runAsUser:
    rule: MustRunAs
    ranges:
      - min: 999
        max: 65535
  volumes:
    - configMap
    - downwardAPI
    - emptyDir
    - projected
    - secret
    - persistentVolumeClaim
    - hostPath

