apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: default-role
rules:
  - apiGroups:
      - "policy"
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames:
      - "default-policy"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: postgres-sa
    apiGroup: ""
    namespace: default
roleRef:
  kind: Role
  name: default-role
  apiGroup: rbac.authorization.k8s.io
